version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

sphinx:
   builder: html
   configuration: conf.py

python:
  install:
    - requirements: docs/requirements.txt